--- #YAML:1.0
name:                CPAN
version:             1.92_64
abstract:            query, download and build perl modules from CPAN sites
license:             perl
author:              
    - Andreas Koenig <andreas.koenig.gmwojprw@franz.ak.mind.de>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Spec:                    0
    File::Temp:                    0
    Scalar::Util:                  0
    Test::Harness:                 2.62
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
repository: "https://pause.perl.org:5460/svn/cpanpm/trunk"
