--- #YAML:1.0
name:               CPAN
version:            2.01-TRIAL
abstract:           query, download and build perl modules from CPAN sites
author:
    - Andreas Koenig <andreas.koenig.gmwojprw@franz.ak.mind.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:        0
    Archive::Zip:        0
    Compress::Bzip2:     0
    Compress::Zlib:      0
    CPAN::Checksums:     0
    CPAN::Meta:          0
    CPAN::Meta::YAML:    0
    Data::Dumper:        0
    Digest::MD5:         0
    Digest::SHA:         0
    ExtUtils::CBuilder:  0
    File::Copy:          0
    File::HomeDir:       0
    File::Spec:          0
    File::Temp:          0
    File::Which:         0
    HTTP::Tiny:          0
    IO::Compress::Base:  0
    IO::Zlib:            0
    JSON::PP:            0
    LWP::UserAgent:      0
    MIME::Base64:        0
    Module::Build:       0
    Module::Signature:   0
    Net::FTP:            0
    Net::Ping:           0
    Parse::CPAN::Meta:   0
    perl:                5.006002
    Scalar::Util:        0
    Term::ReadKey:       0
    Test::Harness:       2.62
    Test::More:          0
    Text::Glob:          0
    Text::ParseWords:    0
    Text::Wrap:          0
    YAML:                0
    YAML::Syck:          0
    YAML::XS:            0
resources:
    repository:  git://github.com/andk/cpanpm.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.5705
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - CPAN
    - module
    - module installation
