--- #YAML:1.0
name:                CPAN
version:             1.87_52
abstract:            query, download and build perl modules from CPAN sites
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_02
author:              Andreas Koenig <andreas.koenig.gmwojprw@franz.ak.mind.de>
distribution_type:   module
requires:     
    File::Spec:                    0
    File::Temp:                    0
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
