--- 
match:
  distribution: "^BRICAS/Catalyst-Plugin-ConfigLoader-\d"
pl: 
  expect:
    - "Auto-install"
    - "y\n"
    - "Auto-install"
    - "y\n"
    - "Auto-install"
    - "y\n"
  env:
    PERL_AUTOINSTALL: --skip    
make:
  env:
    PERL_AUTOINSTALL: --skip    
